- hosts: localhost
  connection: local
  gather_facts: False
  become: false
  vars_files: 
    - vars.yml

  tasks:
    #- name: Create Instance Profile
      #command: >
        #aws iam create-instance-profile --instance-profile-name ec2-demo-hosts
      #environment:
        #AWS_ACCESS_KEY_ID: "{{ lookup('env','AWS_ACCESS_KEY') }}"
        #AWS_SECRET_ACCESS_KEY: "{{ lookup('env','AWS_SECRET_KEY') }}"
    #- name: Add role to instance profile
      #command: >
        #aws iam add-role-to-instance-profile --instance-profile-name ec2-demo-hosts --role-name S3ReadOnlyAccess
      #environment:
        #AWS_ACCESS_KEY_ID: "{{ lookup('env','AWS_ACCESS_KEY') }}"
        #AWS_SECRET_ACCESS_KEY: "{{ lookup('env','AWS_SECRET_KEY') }}"
    - name: Provision a set of instances
      ec2:
        key_name: LinuxKeyPair
        region: us-west-2
        vpc_subnet_id: subnet-42de4824
        group_id: sg-5efc7d23
        instance_type: t2.micro
        instance_profile_name: ec2-demo
        image: "{{ ami_id }}"
        wait: yes 
        exact_count: 2
        count_tag:
          Name: stage-ec2-Demo
        instance_tags:
          Name: stage-ec2-Demo
      register: ec2

    - name: Add all instance public IPs to host group
      add_host: 
        hostname: "{{ item.private_ip }}" 
        groups: ec2hosts
      with_items: "{{ ec2.instances }}"

    - name: add hosts to hosts files
      shell: echo "{{ item.private_ip }}" >> hosts
      with_items: "{{ ec2.instances }}"

    - name: wait 60 seconds and continue
      wait_for: timeout=60
      delegate_to: localhost

    - name: Wait for system to become reachable
      wait_for:
        port: 22

- hosts: ec2hosts
  name: configuration play
  user: ec2-user
  gather_facts: true
  become: true

  tasks:
    - name: Update yum
      shell: yum update -y
    - name: Install NTP Service
      shell: yum install ntp -y
    - name: Install AWS CLI
      shell: |
        yum install python -y
        yum install python-pip -y
        yum install unzip -y
        pip install awscli
    - name: Get S3 bucket listing & download
      shell: |
        BUCKET=nasa-new4
        KEY=`aws s3 ls $BUCKET --recursive | sort | tail -n 1 | awk '{print $4}'`
        aws s3 cp s3://$BUCKET/$KEY ./latest-object.zip
        unzip ./latest-object.zip
        ls -la
        cd latest-object.zip
        pwd
        ls -la