- hosts: localhost
  connection: local
  gather_facts: False
  become: false
  vars_files: 
    - vars.yml

  tasks:
    - name: Provision a set of instances
      ec2:
        key_name: LinuxKeyPair
        region: us-west-2
        vpc_subnet_id: subnet-42de4824
        group_id: sg-5efc7d23
        instance_type: t2.micro
        instance_profile_name: ec2-demo
        image: "{{ ami_id }}"
        wait: yes 
        exact_count: 2
        count_tag:
          Name: test-ec2-Demo
        instance_tags:
          Name: test-ec2-Demo
      register: ec2

    - name: Add all instance public IPs to host group
      add_host: 
        hostname: "{{ item.private_ip }}" 
        groups: ec2hosts
      with_items: "{{ ec2.instances }}"

    - name: add hosts to hosts files
      shell: echo "{{ item.private_ip }}" >> hosts
      with_items: "{{ ec2.instances }}"

    - name: wait 60 seconds and continue
      wait_for: timeout=60
      delegate_to: localhost

    - name: Wait for system to become reachable
      wait_for:
        port: 22

- hosts: ec2hosts
  name: configuration play
  user: ec2-user
  gather_facts: true
  become: true

  tasks:
    - name: Update yum
      shell: yum update -y
    - name: Install PreReqs for Tomcat
      shell: |
        yum install java-1.8.0-openjdk -y
        groupadd tomcat
        mkdir /opt/tomcat
        useradd -s /bin/nologin -g tomcat -d /opt/tomcat tomcat
    - name: Install Tomcat
      shell: |
        cd ~
        wget http://www-us.apache.org/dist/tomcat/tomcat-8/v8.5.33/bin/apache-tomcat-8.5.33.tar.gz
        sudo tar -zxvf apache-tomcat-8.5.33.tar.gz -C /opt/tomcat --strip-components=1
        cd /opt/tomcat
        chgrp -R tomcat conf
        chmod g+rwx conf
        chmod g+r conf/*
        chown -R tomcat logs/ temp/ webapps/ work/
        chgrp -R tomcat bin
        chgrp -R tomcat lib
        chmod g+rwx bin
        chmod g+r bin/*
    - name: Creating Tomcat service file
      copy:
        dest: "/etc/systemd/system/tomcat.service"
        content: |
          [Unit]
          Description=Apache Tomcat Web Application Container
          After=syslog.target network.target

          [Service]
          Type=forking

          Environment=JAVA_HOME=/usr/lib/jvm/jre
          Environment=CATALINA_PID=/opt/tomcat/temp/tomcat.pid
          Environment=CATALINA_HOME=/opt/tomcat
          Environment=CATALINA_BASE=/opt/tomcat
          Environment='CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC'
          Environment='JAVA_OPTS=-Djava.awt.headless=true -Djava.security.egd=file:/dev/./urandom'

          ExecStart=/opt/tomcat/bin/startup.sh
          ExecStop=/bin/kill -15 $MAINPID

          User=tomcat
          Group=tomcat

          [Install]
          WantedBy=multi-user.target
    - name: Start Tomcat
      shell: |
        systemctl start tomcat.service
        systemctl enable tomcat.service
    - name: Setting port forwarding
      shell: |
        iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 8080
        iptables -I INPUT 1 -p tcp --dport 8080 -j ACCEPT
    - name: Install AWS CLI
      shell: |
        yum install python -y
        yum install python-pip -y
        yum install unzip -y
        pip install awscli
    - name: Get S3 bucket listing & download
      shell: |
        BUCKET=nasa-new4
        KEY=`aws s3 ls $BUCKET --recursive | sort | tail -n 1 | awk '{print $4}'`
        aws s3 cp s3://$BUCKET/$KEY ./latest-object.zip
        unzip ./latest-object.zip
        ls -la
        cd latest-object.zip
        pwd
        ls -la